config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/users/:id/reviews', to: 'users#reviews', as: :reviews

  resources :amigo_reviews

  resources :workouts
  get '/join_workout', to: 'workouts#join_workout', as: :join_workout
  post '/book_workout/:id', to: 'workouts#book_workout', as: :book_workout
  get '/upcoming', to: 'workouts#upcoming', as: :upcoming
  get '/menu', to: 'workouts#menu', as: :menu
  post '/complete_workout/:id', to: 'workouts#complete_workout', as: :complete_workout
  get '/completed', to: 'workouts#completed', as: :completed
  get '/awaiting', to: 'workouts#awaiting', as: :awaiting

  resources :gyms, only: [:index, :show]
  get '/search', to: 'gyms#search'

  get '/gym_show_reviews/:id', to: 'gyms#gym_show_reviews', as: :gym_show_reviews

  resources :gym_reviews


  get '/', to: 'application#welcome'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'
  get '/users/:id/profile', to: 'users#profile', as: :profile

end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  belongs_to :amigo, :class_name => "User"
  belongs_to :gym
  has_many :amigo_reviews
  has_many :gym_reviews

  def self.requested
    Workout.all.select do |workout|
      workout.status == 'requested'
    end
  end

  def self.booked(user_id)
    Workout.all.select do |workout|
      workout.status == 'booked' && (workout.user_id == user_id || workout.amigo_id == user_id)
    end
  end

  def self.completed(user_id)

    Workout.all.select do |workout|
      workout.status == "completed" && (workout.user_id == user_id || workout.amigo_id == user_id)
    end
  end

  def self.awaiting(user_id)
    Workout.all.select do |workout|
      workout.status = "requested" && (workout.user_id == user_id)
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :require_login
  layout 'application'


  def menu
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.find(session[:user_id])
    @workout = Workout.new
  end

  def create
    @user = User.find(session[:user_id])
    @workout = Workout.new(workout_params)
    @workout.user_id = @user.id
    @workout.amigo_id = @user.id
    @workout.status = 'requested'
    @workout.save

    redirect_to workout_path(@workout)
  end

  def join_workout
    @workouts = Workout.requested
    render :join_workout
  end

  def book_workout
    @user = User.find(session[:user_id])
    @workout = Workout.find(params[:id])
    @workout.status = 'booked'
    @workout.amigo_id = session[:user_id]
    @workout.save
    render :show
  end

  def upcoming
    @workouts = Workout.booked(session[:user_id])
    render :upcoming
  end

  def completed
    @user = User.find(session[:user_id])
    @workouts = @user.completed
    render :completed
  end

  def awaiting
    @workouts = Workout.completed(session[:user_id])
    render :requested
  end

  def show
    @user = User.find(session[:user_id])
    @workout = Workout.find(params[:id])
  end

  def complete_workout
    @user = User.find(session[:user_id])
    @workout = Workout.find(params[:id])
    @workout.status = 'completed'
    @workout.save
    render :show
  end

  def edit
  end

  def update
  end

  private

  def workout_params
    params.require(:workout).permit(:start_time, :end_time, :description, :gym_id, :user_id, :amigo_id, :status, :date)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/completed.html.erb
<div class = "whole_page">
  <br>
<div class = "page_header"><h2>My Completed Workouts<h2></div><br><br>
<% @workouts.each do |workout| %>
<div class="body">
  <div class="completed_header"><%=workout.date%>: <%= link_to workout.description, workout_path(workout) %> </div><br>
  <div class="review_form">
    <%= form_tag("/gym_reviews") do %>
      <input type="hidden" name="gym_review[gym_id]" value="<%=workout.gym_id%>">
      <input type="hidden" name="gym_review[workout_id]" value="<%=workout.id%>">
      <div class="text">Rate <%=workout.gym.name%>!</div>
        <span class="starRating">
        1 <input id="rating1" type="radio" name="gym_review[rating]" value="1" class="fa fa-star">
        <label for="rating1"></label>
        2 <input id="rating2" type="radio" name="gym_review[rating]" value="2" class="fa fa-star">
        <label for="rating2"></label>
        3 <input id="rating3" type="radio" name="gym_review[rating]" value="3" class="fa fa-star">
        <label for="rating3"></label>
        4 <input id="rating4" type="radio" name="gym_review[rating]" value="4" class="fa fa-star">
        <label for="rating4"></label>
        5 <input id="rating5" type="radio" name="gym_review[rating]" value="5" class="fa fa-star">
        <label for="rating5"></label>
        </span><br>
      <%= text_area_tag "gym_review[description]" %><br>
      <input type="submit" value="submit review">
    <% end%>

    <br><br>

  <%= form_tag("/amigo_reviews") do %>
    <input type="hidden" name="amigo_review[amigo_id]" value="<%=workout.amigo_id%>">
    <input type="hidden" name="amigo_review[workout_id]" value="<%=workout.id%>">
    <div class="text">Rate <%=workout.amigo.username%>!</div>
    <span class="starRating">
    1 <input id="rating1" type="radio" name="amigo_review[rating]" value="1" class="fa fa-star">
    <label for="rating1"></label>
    2 <input id="rating2" type="radio" name="amigo_review[rating]" value="2" class="fa fa-star">
    <label for="rating2"></label>
    3 <input id="rating3" type="radio" name="amigo_review[rating]" value="3" class="fa fa-star">
    <label for="rating3"></label>
    4 <input id="rating4" type="radio" name="amigo_review[rating]" value="4" class="fa fa-star">
    <label for="rating4"></label>
    5 <input id="rating5" type="radio" name="amigo_review[rating]" value="5" class="fa fa-star">
    <label for="rating5"></label>
    </span><br>
    <%= text_area_tag "amigo_review[description]" %><br>
    <input type="submit" value="submit review">
  <% end %>
</div>
</div><br><br>

<% end %>
</div>

app/views/workouts/edit.html.erb
Edit Workout
<%= form_for @workout do |f| %>
  <%= f.label :start_time %>
  <%= f.text_field :start_time %><br>

  <%= f.label :end_time %>
  <%= f.text_field :end_time %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>

app/views/workouts/join_workout.html.erb
<div class = "whole_page">
  <br>
<div class = "page_header"><h2>Workouts Seeking a Partner<h2></div><br><br>
<% joinables = @workouts.select do |workout| %>
<% workout.user_id != session[:user_id]%>
<%end%>
<% if !joinables.empty? %>
<%joinables.each do |workout|%>
  <div class="workout_header"><%=workout.date%>: <%= link_to workout.description, workout_path(workout) %>
<%end%>
<%end%>
  </div></div><br>


</div>
</div><br>

<% if joinables.empty?%>
<div class="workout_header"><%= "No workouts seeking a partner at the moment :/"%><br>
<%= "Create one!"%></div>
<% end%>
</div>

app/views/workouts/new.html.erb
<div class="whole_page">
  <div class="container">
    <br>
    <br>
    <br>
    <h6>
      <div class="new_workout">
      <%= form_for @workout do |f| %>
        <div class="form-group">
          <%= f.label :start_time, class: "form-text"  %>
          <%= f.text_field :start_time, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :end_time, class: "form-text" %>
          <%= f.text_field :end_time, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :date, class: "form-text" %>
          <%= f.text_field :date, placeholder: "dd/mm/yy", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :description, class: "form-text" %>
          <%= f.text_area :description, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.label :gym, class: "form-text" %>
          <%= f.collection_select :gym_id, Gym.all, :id, :name, class: "form-control" %>
        </div>

        </h6>
        <br>
        <br>

        <div class="form-group">
          <%= f.submit :'Create Workout', class: "btn btn-warning" %>
        </div>
      </div>

      <% end %>
</div>
      </div>
</div>

app/views/workouts/requested.html.erb
  <br>
<div class = "awaiting_header"><h2>Workouts I Need A Partner For<h2></div><br><br>
<% @workouts.each do |workout| %>
  <div class="awaiting_body"><%=workout.date%>: <%= link_to workout.description, workout_path(workout) %> </div></div>


</div>
</div><br><br>

<% end %>
</div>

app/views/workouts/show.html.erb
<br>
<div class="workout_show">
Date: <div class="gym-info"><%= @workout.date %></div><br>

Start Time:<div class="gym-info"><%= @workout.start_time %></div><br>
End Time: <div class="gym-info"><%= @workout.end_time %></div><br>
Gym: <div class="gym-info"><%= @workout.gym.name %></div><br>
Gym Address: <div class="gym-info"><%= @workout.gym.address %></div><br>
Workout Description: <div class="gym-info"><%= @workout.description %></div><br>
Workout Status: <div class="gym-info"><%= @workout.status %></div>
<% if @workout.status == 'booked' || @workout.status == "requested"%>
<%= button_to "I completed this workout!", complete_workout_path(@workout)%>
<% end%>
<br>
Created By:
 <% if @workout.user_id == session[:user_id]%>
<div class="gym-info"><%= "Me" %></div>
<% else%>
<div class="gym-info"><%= link_to @workout.user.username, user_path(@workout.user) %></div>
<%end %><br>
Joined By: <% if @workout.user_id == @workout.amigo_id %>
  <div class="gym-info"><%= 'No workout partner yet.' %></div>
  <% elsif @workout.amigo_id == session[:user_id] %>
  <div class="gym-info"><%= 'Me'%></div>
  <% else %>
  <div class="gym-info"><%= @workout.amigo.username %></div><br>
  <% end %>
<% if @workout.user_id == @workout.amigo_id && @workout.user_id != session[:user_id] %>
    <%= button_to 'Join Workout', book_workout_path(@workout)%>
<% end %>
</div>

app/views/workouts/upcoming.html.erb
<br>
<div class="upcoming_body">
  <div class="gym-info">MY UPCOMING WORKOUTS!</div>
<% @workouts.each do |workout| %>
__________________________________________
<br>
  <div class="gym-info"><%= link_to workout.description, workout_path(workout) %></div><br>
  amigos: <div class="gym-info"><%=workout.amigo.username%> & <%=workout.user.username%></div><br>
  on: <div class="gym-info"><%=workout.date%></div>
<% end %>
</div>
<br>