config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/users/:id/reviews', to: 'users#reviews', as: :reviews

  resources :amigo_reviews

  resources :workouts
  get '/join_workout', to: 'workouts#join_workout', as: :join_workout
  post '/book_workout/:id', to: 'workouts#book_workout', as: :book_workout
  get '/upcoming', to: 'workouts#upcoming', as: :upcoming
  get '/menu', to: 'workouts#menu', as: :menu
  post '/complete_workout/:id', to: 'workouts#complete_workout', as: :complete_workout
  get '/completed', to: 'workouts#completed', as: :completed
  get '/awaiting', to: 'workouts#awaiting', as: :awaiting

  resources :gyms, only: [:index, :show]
  get '/search', to: 'gyms#search'

  get '/gym_show_reviews/:id', to: 'gyms#gym_show_reviews', as: :gym_show_reviews

  resources :gym_reviews


  get '/', to: 'application#welcome'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'
  get '/users/:id/profile', to: 'users#profile', as: :profile

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true

  has_many :workouts_initiated, :foreign_key => "user_id", :class_name => "Workout"
  has_many :workouts_joined, :foreign_key => "amigo_id", :class_name => "Workout"
  has_many :gyms, through: :workouts
  has_many :gym_reviews
  has_many :amigo_reviews


  def all_workouts
    all = []
    all << self.workouts_joined
    all << self.workouts_initiated
    all.flatten
    all.uniq
  end

  def completed
    Workout.all.select do |workout|
      (workout.user_id == self.id || workout.amigo_id == self.id) && workout.status == "completed"
    end
  end

  def booked
    Workout.all.select do |workout|
      (workout.user_id == self.id || workout.amigo_id == self.id) && workout.status == "booked"
    end
  end

  def requested
    Workout.all.select do |workout|
      (workout.user_id == self.id || workout.amigo_id == self.id) && workout.status == "requested"
    end
  end

  def reviewed_gym_for_this_workout?(wko_id)
    self.gym_reviews.select do |review|
      review.workout_id = wko_id
    end
  end

  def reviewed_amigo_for_this_workout?(wko_id)
    self.amigo_reviews.select do |review|
      review.workout_id = wko_id
    end
  end

  def reviews
    AmigoReview.all.select do |review|
      review.amigo_id == self.id
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]
  layout 'application'

  def new
    @user = User.new
    byebug
  end

  def create

    @user = User.create(user_params)
    if @user.save
      byebug
      redirect_to profile_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if @user.save
      redirect_to profile_path(@user)
    else
      render :edit
    end
  end

  def profile
    
    @user = User.find(params[:id])
  end

  def show

    @user = User.find(params[:id])
    if !session[:user_id]
      #not logged in!
      @logged = false
    else
      @logged = true
    end

    if @user.id == session[:user_id]
      @self_page = true
    else
      @self_page = false
    end
  end

  def reviews
    @user = User.find(params[:id])
    render :reviews
  end

  private
  def user_params
    params.require(:user).permit(:username, :city, :experience, :goals, :password, :password_confirmation)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class ="container">
  <h1>Edit Profile</h1>
  <% if @user.errors.any? %>
  There were some errors:<br>
  <% @user.errors.full_messages.each do |message| %>
  <%= message %><br>
  <% end %>
  <% end %>
  <br>
  <%= form_for @user do |f| %>
  <div class = "form-group">
    <%= f.label :username, class: "form-text" %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.label :city, class: "form-text" %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.label :experience, class: "form-text" %>
    <%= f.text_field :experience, class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.label :goals, class: "form-text" %>
    <%= f.text_area :goals, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.submit :'Update Profile', class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% byebug %>
<div class="whole_page">
  <br>
  <h1>GYMigo</h1>
  <% if @user.errors.any? %>
  There were some errors:<br>
  <% @user.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
  <% end %>

  <div class="container">
    <div class = "form-group">

        <%= form_for @user do |f| %>
        <h6></span>
        <%= f.label :username, class: "form-text" %>
        <%= f.text_field :username, class: "form-control" %><br>
        <%= f.label :password, class: "form-text" %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation, class: "form-text" %>
        <%= f.password_field :password_confirmation, class: "form-control" %><br>
        </span></h6>
        <%= f.submit :'Sign up!', class: "btn btn-warning" %>
        <% end %>

    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="whole_page">
  <br>
  <div class="page_header"
  <h1>My Profile</h1></div>
        <br>

          <br>
          <div class="body">
          my username: <div class="profile_data"><%= @user.username %></div><br>
          my city: <div class="profile_data"><%= @user.city %></div><br>

         my experience level: <div class="profile_data"><%= @user.experience %></div><br>
          my goals: <div class="profile_data"><%= @user.goals %></div><br>

</div>

<br><br>
<a class="btn btn-danger" href="/users/<%=session[:user_id]%>/edit" role="button">Edit Profile</a>
</div>

app/views/users/reviews.html.erb
<br>
<div class="review_header"><%= @user.username%>'s Reviews</div><br>
<br><br>
<div class="review_body">
<% if @user.reviews%>
<% @user.reviews.each do |review|%>
<br>
rating: <div class="review_info"><%= review.rating%></div><br>
comment: <div class="review_info"><%= review.description%></div><br>
reviewed by: <div class="review_info"><%=review.user.username%></div><br>
<br><%end%>
<% end %>
</div>
</div>
<div class="return_link">
<%= link_to "return to workouts", join_workout_path%>

app/views/users/show.html.erb
<div class="whole_page">
  <br>
  <div class="page_header"
  <h1><%=@user.username%>'s Profile</h1></div>
        <br>

          <br>
          <div class="body">
          username: <div class="profile_data"><%= @user.username %></div><br>
          city: <div class="profile_data"><%= @user.city %></div><br>

         experience level: <div class="profile_data"><%= @user.experience %></div><br>
          goals: <div class="profile_data"><%= @user.goals %></div><br>

</div>
<div class="return_link">
<%= link_to "view #{@user.username}'s reviews'", reviews_path(@user)%>

</div>