config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/users/:id/reviews', to: 'users#reviews', as: :reviews

  resources :amigo_reviews

  resources :workouts
  get '/join_workout', to: 'workouts#join_workout', as: :join_workout
  post '/book_workout/:id', to: 'workouts#book_workout', as: :book_workout
  get '/upcoming', to: 'workouts#upcoming', as: :upcoming
  get '/menu', to: 'workouts#menu', as: :menu
  post '/complete_workout/:id', to: 'workouts#complete_workout', as: :complete_workout
  get '/completed', to: 'workouts#completed', as: :completed
  get '/awaiting', to: 'workouts#awaiting', as: :awaiting

  resources :gyms, only: [:index, :show]
  get '/search', to: 'gyms#search'

  get '/gym_show_reviews/:id', to: 'gyms#gym_show_reviews', as: :gym_show_reviews

  resources :gym_reviews


  get '/', to: 'application#welcome'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'
  get '/users/:id/profile', to: 'users#profile', as: :profile

end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :workouts
  has_many :users, through: :workouts
  has_many :gym_reviews


  def average_rating
    rating_sum = 0
    rating_count = 0
    self.gym_reviews.each do |review|
      rating_sum += review.rating
      rating_count += 1
    end
    if rating_count == 0
      return false
    end
    rating_sum / rating_count
  end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :require_login
  layout 'application'

  def index
    @gyms = Gym.all
    @user = User.find(session[:user_id])
  end

  def show
    @gym = Gym.find(params[:id])
  end

  def search
    @gyms = []
    Gym.all.each do |gym|
      if params[:q] == "all"
        @gyms = Gym.all
      elsif gym.zipcode == params[:q]
        @gyms << gym
      end
    end
    @user = User.find(session[:user_id])
    render :index
  end

  def gym_show_reviews
    @gym = Gym.find(params[:id])
  end 

  private
  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/gym_show_reviews.html.erb
<br>
<div class="container">
  <h1 class="gym_header">
    <div class="text-warning">
      <%= @gym.name %><br>Reviews<br>
      <!-- <div class="gym-address">
        <%= @gym.address + ", " + @gym.city + " " + @gym.zipcode%>
      </div> -->
    </div>
  </h1>

  <p><div class="gym_body">
    <br>
    <!-- OPEN: <div class="gym-info"><%= @gym.hours%></div><br>

    RATES: <div class="gym-info"><%= @gym.rates%></div><br> -->
    <% number = 1 %>
    <% @gym.gym_reviews.each do |review| %>
      <a href="<%=gym_review_path(review)%>" class="btn btn-danger">Review<%=' ' + number.to_s%></a><br><br>
      <% number += 1 %>
    <% end %>
  </div>
</div>

app/views/gyms/index.html.erb
<br>
<div class='container'>
  <!-- <div class="row"> -->


    <div class='container'>

    <div class="col-4" id="text">
        <% if params[:q] %>
        <% if @gyms.empty? %>
        <div class="gym_search_text"><%= "No gyms found in this zipcode." %></div>
        <% else %>
        <div class="gym_search_text"><%= "Gyms in zipcode #{params[:q]}:"%></div>
        <% end %>
        <% end %>
    </div>


  <!-- </div> -->

  <div class="col-6" id="text">
    <% @gyms.each do |gym| %>
    <a href="<%=gym_path(gym)%>" class="badge badge-warning"><%=gym.name%></a>
    <% end %><br><br>
  </div>



  <div class="col-5" id="search">
    <%= form_tag("/search", method: "get") do %>
      <!-- <%= label_tag(:q, "Enter zipcode or 'all' to show all gyms in Search.") %> -->
      <div class="search_bar"><%= text_field_tag(:q, nil, placeholder:"search by zipcode") %></div>
      <div class="search_button"><%= submit_tag("Search", class: "btn btn-danger") %></div>
    <% end %>
  </div>

</div>





    <!-- <div class="col-3.5">
      Enter zipcode or 'all' to show all gyms in Search.
    </div> -->




  </div>
</div>

app/views/gyms/show.html.erb
<br>
<div class="container">
<h1 class="gym_header">
  <div class="text-warning">
    <%= @gym.name %>
    <div class="gym-address">
      <%= @gym.address + ", " + @gym.city + " " + @gym.zipcode%>
      <br>
      Average Rating:
      <% if !@gym.average_rating %>
        No ratings yet.
      <% else %>
        <%= ' ' + @gym.average_rating.round(1).to_s + ' ' %>stars
      <% end %>
    </div>
  </div>
</h1>
<p><div class="gym_body">
  <br>
OPEN: <div class="gym-info"><%= @gym.hours%></div><br>

  RATES: <div class="gym-info"><%= @gym.rates%></div><br>

  <a href="<%=gym_show_reviews_path(@gym)%>" method="post" class="btn btn-danger">Reviews</a>
</div>
</div>